### ISSUE TITLE
Support Gem loading

### ISSUE THREAD

**Issue by davhdavh** [gemforce-team/ManaMason#1]
It would be really nice if ManaMason also supported inserting gems.
I suggest that it could be done by appending lines like this:
1=y 10 2
meaning that in the first structure, we load a yellow gem of grade 10 with targeting set to option 2 (swarmlings).

**Comment by davhdavh** [comment]
Might be useful to support "_=y 10 2" also, to just mean "next" structure, so you dont have to keep track of the numbering.

**Comment by hellrage** [comment]
Hello!
Yep, filling the buildings with gems is in the plans! Thanks for the input, I was wondering how to encode the gems and this is helpful.

**Comment by Scowley4** [comment]
As another idea, since each gem-structure takes up 4 spaces:

```
aattaa
aattaa
tttttt
tttttt

y1y2y1 <-yellow gems, set to Nearest to Orb
050705 <- grades 5, 7, and 5
b5o4o4 <- blue to Least affected... and orange set to Random
031212 <- grades 3, 12, and 12
```

Though may be a good idea to just remove all extra whitespace so we could make them more readable:
```
y1 y2 y1 <-yellow gems, set to Nearest to Orb
05 07 05 <- grades 5, 7, and 5
b5 o4 o4 <- blue to Least affected... and orange set to Random
03 12 12 <- grades 3, 12, and 12
```

Just an idea. Love what you've done so far =)

**Comment by hellrage** [comment]
Like I mentioned on Discord, I'm considering something like:
```
aatt
01tt
rraa
02aa

Id=[r,g,b,y,o,p,gs,inv] [grade,gs filename,slot index] [targetting]
01=r 10 1 //red gem of grade 10 with...um, some targetting 😄 
02=gs lc000008 2 //Gesmith-conjured gem with that recipe and some targetting
Gemsmith will probably need ""speccing"" support (conjuring a gem from scratch)
02=inv 8 3 //Take a gem from the last inventory slot with some targetting
```
Where the numbers inside structures are gem Ids. So we'll have trailing lines in the blueprint describing the gems. That way you can reuse the same Id in several buildings without having to copypaste the descriptions.

I'll probably get to it this weekend, otherwise there's another person who was interested in implementing it and PRing here!

**Comment by hellrage** [comment]
Full support added in 87d54e20873ab19686c8cd22ab73f88263e6abf2
Check the readme for details!
Thanks for your suggestions!
