### ISSUE TITLE
Splitting blueprints on carriage return (\r)

### ISSUE THREAD

**Issue by Scowley4** [gemforce-team/ManaMason#2]
https://github.com/gemforce-team/ManaMason/blob/bb32f93750e9cb7d2e2c11272a1deaefe385266e/src/ManaMason/Blueprint.as#L43

Could we allow splitting on `\r\n` as well as just `\n`?

**Comment by hellrage** [comment]
Hello! Yeah, I'll take a look.
Also oops, leftover 'recipe' name from Gemsmith recipes!

**Comment by hellrage** [comment]
Blueprints are now split on line endings (as per AS3 `File.lineEnding` cross-platform implementation).
87d54e20873ab19686c8cd22ab73f88263e6abf2
